### ISSUE TITLE
[2pt] Milestone 1: Login page and registration page

### ISSUE THREAD

**Issue by mershark** [mershark/recipe-app#2]
- [x]  Can register a new user.
- [x]  User logs in with a combination of email and password.
- [x]  Hashed password should be stored in the database.
- [x]  Ask for confirmation of email.
- [x]  Can reset password.
