### ISSUE TITLE
[1pt] Milestone 2: Food list (only for a group that has less than 3 members)

### ISSUE THREAD

**Issue by mershark** [mershark/recipe-app#3]
- [x] Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
- [x]  Should lead to a form that allows users to add new food.
- [x]  If the user is the owner of the recipe, should allow the user to delete it.
